version: '3.5'
services:
  db:
    container_name: projeqtor-postgresql
    image: postgres
    volumes:
      - db-data:/data/postgres
    ports:
      - "${POSTGRES_PORT}:5432"
    restart: unless-stopped
    environment:
      - POSTGRES_DB: 'projeqtor'
      - POSTGRES_USER: 'projeqtor'
      - POSTGRES_PASSWORD: 'projeqtor'
      - PG_DATA: '/data/postgres'
      - POSTGRES_PORT: '5432'
      - POSTGRES_VERSION: 'latest'
  
  projeqtor:
    image: sailman/projeqtor
    build:
      dockerfile: "./docker/.Dockerfile"
    container_name: projeqtor
    volumes:
      - "./php/php.ini:/usr/local/etc/php/php.ini:ro"
      - "./log/projeqtor:${PROJEQTOR_LOG_PATH}:rw"
      - "./app/config:${PROJEQTOR_CONFIG_PATH}:rw"
  
